import { assets } from "@/assets/asset";

export const articles: Record<BlogCategory, Article[]> = {
  tech: [
    {
      title: "5 Digital Tools Every Nigerian Farmer Should Be Using in 2025",
      time: "10-15 Minutes read",
      description:
        "Digital tools are transforming farming in Nigeria by helping farmers make faster, smarter, and more profitable decisions.",
      author: "Musa Aliyu",
      date: "February, 2025",
      image: assets.digitaltools,
    },
    {
      title: "How Mobile Phones Are Changing the Way Farmers Trade",
      time: "10-15 Minutes read",
      description:
        "Mobile phones have completely transformed how farmers trade by giving them instant access to buyers and market information.",
      author: "Musa Aliyu",
      date: "February, 2025",
      image: assets.smarttrade,
    },
  ],
  business: [
    {
      title:
        "Everything You Need to Know About Sourcing Fresh Tomatoes in Bulk",
      time: "10-15 Minutes read",
      description:
        "Fresh tomatoes are one of the most in-demand produce items, but sourcing them in bulk requires knowing the right seasons and trusted suppliers.",
      author: "Adewale Adegoke",
      date: "January, 2025",
      image: assets.tomatoes,
    },
    {
      title: "How Cooperatives Can Boost Farmer Negotiation Power in Nigeria",
      time: "10-15 Minutes read",
      description:
        "Cooperatives help farmers negotiate better prices by pooling their produce and sharing market information.",
      author: "Bunmi Alonge",
      date: "April, 2025",
      image: assets.cooperativeboast,
    },
  ],
  farm: [
    {
      title: "How to Choose the Right Seeds for Your Soil Type in Nigeria",
      time: "10-15 Minutes read",
      description:
        "Choosing the right seeds starts with understanding your soil type—whether it's sandy, loamy, or clay—because each crop grows best in specific conditions.",
      author: "Adewale Adegoke",
      date: "January, 2025",
      image: assets.rightsoil,
    },
  ],
};

export const blogCategories = [
  { id: "tech", name: "Tech", count: articles.tech.length },
  { id: "business", name: "Business", count: articles.business.length },
  { id: "farm", name: "Farm Education", count: articles.farm.length },
] as const;

export const categories: Category[] = [
  { id: 1, name: "Protein", imageUrl: assets.protein },
  { id: 2, name: "Vegetables", imageUrl: assets.vegetable },
  { id: 3, name: "Grains", imageUrl: assets.grains },
  { id: 4, name: "Nuts", imageUrl: assets.nuts },
  { id: 5, name: "Fruits", imageUrl: assets.fruits },
  { id: 6, name: "Roots & Tubers", imageUrl: assets.roots },
];

export const sellers: Seller[] = [
  {
    id: 1,
    name: "Ogunrunu Ashim",
    location: "Osun, Nigeria",
    avatar: "/sellers/ashim.jpg",
  },
  {
    id: 2,
    name: "Agrip Farm",
    location: "Lagos, Nigeria",
    avatar: "/sellers/fatimah.jpg",
  },
  {
    id: 3,
    name: "Twin Farm",
    location: "Osun, Nigeria",
    avatar: "/sellers/chinedu.jpg",
  },
  {
    id: 4,
    name: "Aisha Yusuf",
    location: "Lagos, Nigeria",
    avatar: "/sellers/aisha.jpg",
  },
  {
    id: 5,
    name: "Kunle Adeyemi",
    location: "Oyo, Nigeria",
    avatar: "/sellers/kunle.jpg",
  },
  {
    id: 6,
    name: "Lade Farm",
    location: "Oyo, Nigeria",
    avatar: "/sellers/grace.jpg",
  },
];
export const products: Product[] = [
  // --- Category 1: Protein ---
  {
    id: 101,
    name: "Chicken Breast",
    categoryId: 1,
    price: 8.99,
    imageUrl: "/products/chicken.jpg",
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Corporate",
    seller: sellers[5],
  },
  {
    id: 102,
    name: "Salmon Fillet",
    categoryId: 1,
    price: 12.5,
    imageUrl: "/products/salmon.jpg",
    condition: "Frozen",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 103,
    name: "Tofu Block",
    categoryId: 1,
    price: 3.5,
    imageUrl: "/products/tofu.jpg",
    condition: "Processed",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 104,
    name: "Lentils (Bag)",
    categoryId: 1,
    price: 2.99,
    imageUrl: "/products/lentils.jpg",
    condition: "Dried",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 105,
    name: "Ground Beef (Lean)",
    categoryId: 1,
    price: 7.25,
    imageUrl: "/products/ground-beef.jpg",
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 106,
    name: "Eggs (Dozen)",
    categoryId: 1,
    price: 4.0,
    imageUrl: "/products/eggs.jpg",
    condition: "Fresh",
    location: "Osun",
    sellerType: "Corporate",
    seller: sellers[2],
  },

  // --- Category 2: Vegetables ---
  {
    id: 201,
    name: "Carrot (Bunch)",
    categoryId: 2,
    price: 1.2,
    imageUrl: "/products/carrot.jpg",
    condition: "Organic",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 202,
    name: "Broccoli Crown",
    categoryId: 2,
    price: 2.5,
    imageUrl: "/products/broccoli.jpg",
    condition: "Fresh",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 203,
    name: "Spinach (Bag)",
    categoryId: 2,
    price: 3.0,
    imageUrl: "/products/spinach.jpg",
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 204,
    name: "Bell Peppers (3-Pack)",
    categoryId: 2,
    price: 4.5,
    imageUrl: "/products/bell-peppers.jpg",
    condition: "Fresh",
    location: "Lagos",
    sellerType: "Individual",
    seller: sellers[3],
  },
  {
    id: 205,
    name: "Head of Lettuce",
    categoryId: 2,
    price: 1.75,
    imageUrl: "/products/lettuce.jpg",
    condition: "Organic",
    location: "Osun",
    sellerType: "Corporate",
    seller: sellers[2],
  },
  {
    id: 206,
    name: "Zucchini",
    categoryId: 2,
    price: 0.99,
    imageUrl: "/products/zucchini.jpg",
    condition: "Fresh",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },

  // --- Category 3: Grains ---
  {
    id: 301,
    name: "Brown Rice (Bag)",
    categoryId: 3,
    price: 5.5,
    imageUrl: "/products/brown-rice.jpg",
    condition: "Dried",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 302,
    name: "Oatmeal (Container)",
    categoryId: 3,
    price: 3.99,
    imageUrl: "/products/oatmeal.jpg",
    condition: "Processed",
    location: "Oyo",
    sellerType: "Corporate",
    seller: sellers[5],
  },
  {
    id: 303,
    name: "Quinoa (Box)",
    categoryId: 3,
    price: 6.75,
    imageUrl: "/products/quinoa.jpg",
    condition: "Dried",
    location: "Lagos",
    sellerType: "Individual",
    seller: sellers[3],
  },
  {
    id: 304,
    name: "Whole Wheat Bread",
    categoryId: 3,
    price: 3.2,
    imageUrl: "/products/wheat-bread.jpg",
    condition: "Processed",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 305,
    name: "Pasta (Penne)",
    categoryId: 3,
    price: 1.99,
    imageUrl: "/products/pasta.jpg",
    condition: "Dried",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 306,
    name: "Cornmeal",
    categoryId: 3,
    price: 2.5,
    imageUrl: "/products/cornmeal.jpg",
    condition: "Processed",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },

  // --- Category 4: Nuts ---
  {
    id: 401,
    name: "Almonds (Roasted)",
    categoryId: 4,
    price: 9.5,
    imageUrl: "/products/almonds.jpg",
    condition: "Processed",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 402,
    name: "Walnuts (Halves)",
    categoryId: 4,
    price: 10.99,
    imageUrl: "/products/walnuts.jpg",
    condition: "Dried",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 403,
    name: "Cashews (Raw)",
    categoryId: 4,
    price: 11.2,
    imageUrl: "/products/cashews.jpg",
    condition: "Organic",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 404,
    name: "Peanut Butter (Jar)",
    categoryId: 4,
    price: 4.0,
    imageUrl: "/products/peanut-butter.jpg",
    condition: "Processed",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 405,
    name: "Pistachios (Shelled)",
    categoryId: 4,
    price: 13.5,
    imageUrl: "/products/pistachios.jpg",
    condition: "Dried",
    location: "Lagos",
    sellerType: "Corporate",
    seller: sellers[1],
  },
  {
    id: 406,
    name: "Mixed Nuts",
    categoryId: 4,
    price: 10.0,
    imageUrl: "/products/mixed-nuts.jpg",
    condition: "Processed",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },

  // --- Category 5: Fruits ---
  {
    id: 501,
    name: "WaterMelon (Single)",
    categoryId: 5,
    price: 0.5,
    imageUrl: assets.watermelon,
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 502,
    name: "Banana (Bunch)",
    categoryId: 5,
    price: 0.3,
    imageUrl: assets.banana,
    condition: "Fresh",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 503,
    name: "Mango (basket)",
    categoryId: 5,
    price: 3.75,
    imageUrl: assets.mango,
    condition: "Organic",
    location: "Lagos",
    sellerType: "Individual",
    seller: sellers[3],
  },
  {
    id: 504,
    name: "Orange (Single)",
    categoryId: 5,
    price: 0.75,
    imageUrl: assets.orange,
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 505,
    name: "Pawpaw (Single)",
    categoryId: 5,
    price: 4.25,
    imageUrl: assets.pawpaw,
    condition: "Fresh",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 506,
    name: "Avocado",
    categoryId: 5,
    price: 1.5,
    imageUrl: "/products/avocado.jpg",
    condition: "Organic",
    location: "Lagos",
    sellerType: "Individual",
    seller: sellers[3],
  },

  // --- Category 6: Roots & Tubers ---
  {
    id: 601,
    name: "Sweet Potatoes (Bag)",
    categoryId: 6,
    price: 3.0,
    imageUrl: "/products/sweet-potatoes.jpg",
    condition: "Fresh",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 602,
    name: "White Potatoes (Bag)",
    categoryId: 6,
    price: 2.5,
    imageUrl: "/products/white-potatoes.jpg",
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 603,
    name: "Ginger Root",
    categoryId: 6,
    price: 1.5,
    imageUrl: "/products/ginger.jpg",
    condition: "Organic",
    location: "Lagos",
    sellerType: "Individual",
    seller: sellers[3],
  },
  {
    id: 604,
    name: "Onions (Yellow, Bag)",
    categoryId: 6,
    price: 2.0,
    imageUrl: "/products/onions.jpg",
    condition: "Dried",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
  {
    id: 605,
    name: "Garlic (Bulb)",
    categoryId: 6,
    price: 0.75,
    imageUrl: "/products/garlic.jpg",
    condition: "Dried",
    location: "Osun",
    sellerType: "Individual",
    seller: sellers[0],
  },
  {
    id: 606,
    name: "Yams",
    categoryId: 6,
    price: 3.5,
    imageUrl: "/products/yams.jpg",
    condition: "Fresh",
    location: "Oyo",
    sellerType: "Individual",
    seller: sellers[4],
  },
];
