import { assets } from "@/assets/asset";

export const categories: Category[] = [
  { id: 1, name: "Protein", imageUrl: assets.protein },
  { id: 2, name: "Vegetables", imageUrl: assets.vegetable },
  { id: 3, name: "Grains", imageUrl: assets.grains },
  { id: 4, name: "Nuts", imageUrl: assets.nuts },
  { id: 5, name: "Fruits", imageUrl: assets.fruits },
  { id: 6, name: "Roots & Tubers", imageUrl: assets.roots },
];
export const products: Product[] = [
  // --- Category 1: Protein ---
  {
    id: 101,
    name: "Chicken Breast",
    categoryId: 1,
    price: 8.99,
    imageUrl: "/products/chicken.jpg",
  },
  {
    id: 102,
    name: "Salmon Fillet",
    categoryId: 1,
    price: 12.5,
    imageUrl: "/products/salmon.jpg",
  },
  {
    id: 103,
    name: "Tofu Block",
    categoryId: 1,
    price: 3.5,
    imageUrl: "/products/tofu.jpg",
  },
  {
    id: 104,
    name: "Lentils (Bag)",
    categoryId: 1,
    price: 2.99,
    imageUrl: "/products/lentils.jpg",
  },
  {
    id: 105,
    name: "Ground Beef (Lean)",
    categoryId: 1,
    price: 7.25,
    imageUrl: "/products/ground-beef.jpg",
  },
  {
    id: 106,
    name: "Eggs (Dozen)",
    categoryId: 1,
    price: 4.0,
    imageUrl: "/products/eggs.jpg",
  },

  // --- Category 2: Vegetables ---
  {
    id: 201,
    name: "Carrot (Bunch)",
    categoryId: 2,
    price: 1.2,
    imageUrl: "/products/carrot.jpg",
  },
  {
    id: 202,
    name: "Broccoli Crown",
    categoryId: 2,
    price: 2.5,
    imageUrl: "/products/broccoli.jpg",
  },
  {
    id: 203,
    name: "Spinach (Bag)",
    categoryId: 2,
    price: 3.0,
    imageUrl: "/products/spinach.jpg",
  },
  {
    id: 204,
    name: "Bell Peppers (3-Pack)",
    categoryId: 2,
    price: 4.5,
    imageUrl: "/products/bell-peppers.jpg",
  },
  {
    id: 205,
    name: "Head of Lettuce",
    categoryId: 2,
    price: 1.75,
    imageUrl: "/products/lettuce.jpg",
  },
  {
    id: 206,
    name: "Zucchini",
    categoryId: 2,
    price: 0.99,
    imageUrl: "/products/zucchini.jpg",
  },

  // --- Category 3: Grains ---
  {
    id: 301,
    name: "Brown Rice (Bag)",
    categoryId: 3,
    price: 5.5,
    imageUrl: "/products/brown-rice.jpg",
  },
  {
    id: 302,
    name: "Oatmeal (Container)",
    categoryId: 3,
    price: 3.99,
    imageUrl: "/products/oatmeal.jpg",
  },
  {
    id: 303,
    name: "Quinoa (Box)",
    categoryId: 3,
    price: 6.75,
    imageUrl: "/products/quinoa.jpg",
  },
  {
    id: 304,
    name: "Whole Wheat Bread",
    categoryId: 3,
    price: 3.2,
    imageUrl: "/products/wheat-bread.jpg",
  },
  {
    id: 305,
    name: "Pasta (Penne)",
    categoryId: 3,
    price: 1.99,
    imageUrl: "/products/pasta.jpg",
  },
  {
    id: 306,
    name: "Cornmeal",
    categoryId: 3,
    price: 2.5,
    imageUrl: "/products/cornmeal.jpg",
  },

  // --- Category 4: Nuts ---
  {
    id: 401,
    name: "Almonds (Roasted)",
    categoryId: 4,
    price: 9.5,
    imageUrl: "/products/almonds.jpg",
  },
  {
    id: 402,
    name: "Walnuts (Halves)",
    categoryId: 4,
    price: 10.99,
    imageUrl: "/products/walnuts.jpg",
  },
  {
    id: 403,
    name: "Cashews (Raw)",
    categoryId: 4,
    price: 11.2,
    imageUrl: "/products/cashews.jpg",
  },
  {
    id: 404,
    name: "Peanut Butter (Jar)",
    categoryId: 4,
    price: 4.0,
    imageUrl: "/products/peanut-butter.jpg",
  },
  {
    id: 405,
    name: "Pistachios (Shelled)",
    categoryId: 4,
    price: 13.5,
    imageUrl: "/products/pistachios.jpg",
  },
  {
    id: 406,
    name: "Mixed Nuts",
    categoryId: 4,
    price: 10.0,
    imageUrl: "/products/mixed-nuts.jpg",
  },

  // --- Category 5: Fruits ---
  {
    id: 501,
    name: "WaterMelon (Single)",
    categoryId: 5,
    price: 0.5,
    imageUrl: assets.watermelon,
  },
  {
    id: 502,
    name: "Banana (Bunch)",
    categoryId: 5,
    price: 0.3,
    imageUrl: assets.banana,
  },
  {
    id: 503,
    name: "Mango (basket)",
    categoryId: 5,
    price: 3.75,
    imageUrl: assets.mango,
  },
  {
    id: 504,
    name: "Orange (Single)",
    categoryId: 5,
    price: 0.75,
    imageUrl: assets.orange,
  },
  {
    id: 505,
    name: "Pawpaw (Single)",
    categoryId: 5,
    price: 4.25,
    imageUrl: assets.pawpaw,
  },
  {
    id: 506,
    name: "Avocado",
    categoryId: 5,
    price: 1.5,
    imageUrl: "/products/avocado.jpg",
  },

  // --- Category 6: Roots & Tubers ---
  {
    id: 601,
    name: "Sweet Potatoes (Bag)",
    categoryId: 6,
    price: 3.0,
    imageUrl: "/products/sweet-potatoes.jpg",
  },
  {
    id: 602,
    name: "White Potatoes (Bag)",
    categoryId: 6,
    price: 2.5,
    imageUrl: "/products/white-potatoes.jpg",
  },
  {
    id: 603,
    name: "Ginger Root",
    categoryId: 6,
    price: 1.5,
    imageUrl: "/products/ginger.jpg",
  },
  {
    id: 604,
    name: "Onions (Yellow, Bag)",
    categoryId: 6,
    price: 2.0,
    imageUrl: "/products/onions.jpg",
  },
  {
    id: 605,
    name: "Garlic (Bulb)",
    categoryId: 6,
    price: 0.75,
    imageUrl: "/products/garlic.jpg",
  },
  {
    id: 606,
    name: "Yams",
    categoryId: 6,
    price: 3.5,
    imageUrl: "/products/yams.jpg",
  },
];
